# Generated by Django 5.2.5 on 2025-08-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.BooleanField(default=False),
        ),
    ]
