# Generated by Django 5.2.5 on 2025-08-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lead_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='drop',
            field=models.BooleanField(default=False),
        ),
    ]
