# Generated by Django 5.2.5 on 2025-08-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_drop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
