# Generated by Django 5.2.5 on 2025-08-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='assign_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
