# Generated by Django 5.2.5 on 2025-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailmessage_created_by_message_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
