# Generated by Django 5.2.5 on 2025-08-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailmessage_read_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_acquired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission',
        ),
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
