# Generated by Django 5.2.5 on 2025-08-23 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_user_client_acquired_remove_user_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+233\\d{9}$', message='Enter a valid WhatsApp number in the format +233XXXXXXXXX (e.g., +233591234567).')]),
        ),
    ]
