# Generated by Django 5.2.5 on 2025-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
